# Generated by Django 5.0.2 on 2024-04-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="requires_delivery",
            field=models.BooleanField(default=False, verbose_name="Доставка"),
        ),
    ]
